// AI Tools Database - 100 Curated Tools with Details
const aiTools = [
    {
        id: "chatgpt",
        name: "ChatGPT",
        description: "A powerful conversational AI that can write, code, and assist with complex tasks.",
        longDescription: "ChatGPT is an advanced language model developed by OpenAI. It is designed to generate human-like text based on the prompts provided by users. It can assist with a wide range of tasks including writing essays, generating code, translating languages, and answering complex questions across various domains.",
        features: ["Advanced Natural Language Processing", "Multi-language Support", "Code Generation & Debugging", "Creative Writing Assistance"],
        category: "writing",
        link: "https://chat.openai.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "midjourney",
        name: "Midjourney",
        description: "An AI-powered system that creates high-quality images from text descriptions.",
        longDescription: "Midjourney is an independent research lab exploring new mediums of thought and expanding the imaginative powers of the human species. Their AI tool generates stunning, artistic images from simple text prompts, primarily through a Discord-based interface.",
        features: ["High-Resolution Artistic Generation", "Vast Community Gallery", "Detailed Parameter Control", "Fast & Relaxed Generation Modes"],
        category: "image",
        link: "https://www.midjourney.com",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "github-copilot",
        name: "GitHub Copilot",
        description: "Your AI pair programmer that helps you write code faster and with less work.",
        longDescription: "GitHub Copilot uses the OpenAI Codex to suggest code and entire functions in real-time, right from your editor. It's trained on billions of lines of public code, turning natural language prompts into coding suggestions across dozens of languages.",
        features: ["Real-time Code Suggestions", "Natural Language to Code", "Unit Test Generation", "Support for Multiple IDEs"],
        category: "coding",
        link: "https://github.com/features/copilot",
        badge: "new",
        pricing: "Paid"
    },
    {
        id: "elevenlabs",
        name: "ElevenLabs",
        description: "The most realistic AI text-to-speech and voice cloning software.",
        longDescription: "ElevenLabs brings the most compelling, rich, and lifelike voices to creators and publishers seeking the ultimate tools for storytelling. Their Deep Learning model renders human intonation and inflections with unsurpassed fidelity.",
        features: ["Ultra-Realistic Voice Synthesis", "Voice Cloning Technology", "Multi-lingual Support", "Emotional Range Control"],
        category: "audio",
        link: "https://elevenlabs.io",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "runway-gen2",
        name: "Runway Gen-2",
        description: "A multi-modal AI system that can generate novel videos with text, images, or video clips.",
        longDescription: "Gen-2 is a multi-modal AI system that can generate novel videos with text, images, or video clips. It represents a massive leap forward in creative tools, allowing anyone to generate cinematic content from a simple prompt.",
        features: ["Text-to-Video Generation", "Image-to-Video Transformation", "Style Transfer", "Advanced Motion Control"],
        category: "video",
        link: "https://runwayml.com",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "claude",
        name: "Claude",
        description: "A next-generation AI assistant for your tasks, no matter the scale.",
        longDescription: "Claude is a next-generation AI assistant from Anthropic based on their research into training helpful, honest, and harmless AI systems. Claude is capable of a wide variety of conversational and text processing tasks.",
        features: ["Large Context Window", "Constitutional AI Safety", "Complex Reasoning", "Document Analysis"],
        category: "writing",
        link: "https://claude.ai",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "perplexity",
        name: "Perplexity AI",
        description: "An AI-powered search engine that provides direct answers to questions with citations.",
        longDescription: "Perplexity AI is an answer engine that delivers accurate, trusted, and real-time answers to any question. It uses large language models to search the web and provide comprehensive answers with source citations.",
        features: ["Real-time Web Search", "Source Citations", "Follow-up Questions", "Conversational Interface"],
        category: "productivity",
        link: "https://perplexity.ai",
        badge: "trending",
        pricing: "Free"
    },
    {
        id: "canva-magic",
        name: "Canva Magic Studio",
        description: "All the power of AI, all in one place in Canva for design and creativity.",
        longDescription: "Canva Magic Studio brings the world's most innovative AI tools together in one place. From generating images to transforming text into presentations, it makes high-end design accessible to everyone.",
        features: ["Magic Media (Text-to-Image/Video)", "Magic Expand & Edit", "Magic Switch for Formats", "Instant Presentations"],
        category: "image",
        link: "https://canva.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "suno",
        name: "Suno AI",
        description: "Make any song you can imagine with Suno AI, the best AI music generator.",
        longDescription: "Suno is building a future where anyone can make great music. Whether you're a shower singer or a charting artist, Suno breaks down barriers between you and the song you dream of making.",
        features: ["Complete Song Generation", "Vocal & Instrumental Production", "Diverse Genre Support", "High-Fidelity Audio"],
        category: "audio",
        link: "https://suno.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "deepl",
        name: "DeepL",
        description: "The world's most accurate translator, powered by neural networks.",
        longDescription: "DeepL's neural networks are able to capture even the slightest nuances and reproduce them in translation, making it far superior to other translation services for professional use.",
        features: ["Highly Accurate Translation", "Glossary for Custom Terms", "Document Translation (PDF/Word)", "Tone Selection (Formal/Informal)"],
        category: "productivity",
        link: "https://deepl.com",
        badge: "",
        pricing: "Free"
    },
    {
        id: "leonardo",
        name: "Leonardo.ai",
        description: "Create production-quality visual assets for your projects with unprecedented speed.",
        longDescription: "Leonardo.ai provides a full-stack platform for AI-driven creative production. It allows creators to generate high-quality images, train their own models, and maintain consistent styles across projects.",
        features: ["Custom Model Training", "Real-time Canvas Editor", "Texture Generation for 3D", "High-End Image Upscaling"],
        category: "image",
        link: "https://leonardo.ai",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "v0",
        name: "v0.dev",
        description: "Generative UI system by Vercel to build professional websites with simple prompts.",
        longDescription: "v0 is an AI-powered generative UI system by Vercel that allows developers to create beautiful, accessible React components and layouts using simple natural language prompts.",
        features: ["Component Generation", "Shadcn UI Integration", "Instant Preview", "Code Export"],
        category: "coding",
        link: "https://v0.dev",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "heygen",
        name: "HeyGen",
        description: "Scale your video production with AI-generated avatars and seamless translations.",
        longDescription: "HeyGen is an innovative AI video platform that helps you create professional business videos with customizable AI avatars in minutes. No camera or crew needed.",
        features: ["AI Avatar Generation", "Video Translation", "Talking Photos", "Text-to-Video"],
        category: "video",
        link: "https://heygen.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "adobe-firefly",
        name: "Adobe Firefly",
        description: "Generative AI for creators, integrated directly into Adobe Photoshop and Illustrator.",
        longDescription: "Adobe Firefly is a family of creative generative AI models that allow you to generate images, text effects, and more from simple prompts, with a focus on commercially safe content.",
        features: ["Generative Fill in Photoshop", "Text to Vector Graphic", "Generative Recolor", "Text Effects"],
        category: "image",
        link: "https://www.adobe.com/sensei/generative-ai/firefly.html",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "cursor",
        name: "Cursor",
        description: "The AI-first code editor designed to make you exceptionally productive at software development.",
        longDescription: "Cursor is a fork of VS Code that integrates AI at its core. It understands your codebase and helps you write, edit, and navigate code with remarkable efficiency.",
        features: ["Codebase Awareness", "AI-Powered Refactoring", "Automated Bug Fixing", "Chat with Files"],
        category: "coding",
        link: "https://cursor.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "notion-ai",
        name: "Notion AI",
        description: "Work faster, write better, and think bigger with AI integrated directly into your workspace.",
        longDescription: "Notion AI is a suite of tools built into Notion that help you write, brainstorm, summarize, and find information across your entire workspace.",
        features: ["Content Summarization", "Writing Assistance", "Action Item Extraction", "Database Automation"],
        category: "productivity",
        link: "https://www.notion.so/product/ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "grammarly-go",
        name: "GrammarlyGO",
        description: "Generative AI that helps you write, rewrite, and brainstorm with personalized voice.",
        longDescription: "GrammarlyGO is a generative AI communication assistant that helps you write, rewrite, brainstorm, and reply to emails in a way that sounds like you.",
        features: ["Context-Aware Rewriting", "Tone Adjustment", "Idea Brainstorming", "Personalized Voice Profiles"],
        category: "writing",
        link: "https://www.grammarly.com/grammarlygo",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "descript",
        name: "Descript",
        description: "A new way to make video and podcasts by editing text instead of audio clips.",
        longDescription: "Descript is an all-in-one video and podcast editor that makes editing as easy as a word doc. It transcribes your audio and lets you edit the media by editing the transcript.",
        features: ["Transcript-Based Editing", "AI Voice Overdub", "Studio Sound Enhancement", "Automatic Filler Word Removal"],
        category: "audio",
        link: "https://www.descript.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "copy-ai",
        name: "Copy.ai",
        description: "AI-powered copywriting tool for marketing, social media, and business growth.",
        longDescription: "Copy.ai is a GTM AI platform that helps teams automate their sales and marketing workflows. It creates high-converting content for ads, social media, and websites.",
        features: ["Marketing Workflow Automation", "Content Generation", "Brand Voice Integration", "Sales Outreach Personalization"],
        category: "writing",
        link: "https://www.copy.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "jasper",
        name: "Jasper",
        description: "AI content generator for teams that creates high-quality content 10x faster.",
        longDescription: "Jasper is the generative AI platform for enterprise marketing teams. It helps teams create high-quality content and images that stay on-brand across every channel.",
        features: ["Enterprise-Grade Content", "Brand Voice Memory", "Multi-language Generation", "SEO Content Integration"],
        category: "writing",
        link: "https://www.jasper.ai",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "luma-dream-machine",
        name: "Luma Dream Machine",
        description: "A highly capable AI model that makes high-quality, realistic videos from text and images.",
        longDescription: "Dream Machine is a powerful video generation model that creates high-quality, realistic 5-second videos from simple text descriptions and images.",
        features: ["Cinematic Quality Video", "Realistic Motion", "Text & Image to Video", "Fast Generation Times"],
        category: "video",
        link: "https://lumalabs.ai/dream-machine",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "replicate",
        name: "Replicate",
        description: "Run machine learning models in the cloud with an API, from text-to-image to voice.",
        longDescription: "Replicate makes it easy to run machine learning models in your apps. You can find and use open-source models for image generation, language processing, and more via their API.",
        features: ["API Access to ML Models", "Scalable Infrastructure", "Diverse Model Library", "Developer Friendly Tooling"],
        category: "coding",
        link: "https://replicate.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "fireflies-ai",
        name: "Fireflies.ai",
        description: "AI meeting assistant that automatically records, transcribes, and summarizes meetings.",
        longDescription: "Fireflies.ai is an AI meeting assistant that helps your team record, transcribe, search, and analyze voice conversations across several web conferencing platforms.",
        features: ["Automatic Transcription", "Smart Summaries", "Conversation Analytics", "Integration with Zoom/Teams/Meet"],
        category: "productivity",
        link: "https://fireflies.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "tome",
        name: "Tome",
        description: "AI-powered storytelling platform to create compelling presentations and landing pages.",
        longDescription: "Tome is the world's first generative storytelling format. It uses AI to generate entire presentations from a single prompt, complete with text, images, and layout.",
        features: ["Generative Presentation Design", "Dynamic Layout Creation", "Interactive Tiles", "Mobile Responsive Pages"],
        category: "productivity",
        link: "https://tome.app",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "otter-ai",
        name: "Otter.ai",
        description: "Get an AI meeting assistant that records audio, writes notes, and captures action items.",
        longDescription: "Otter.ai provides an AI-powered meeting assistant that records, transcribes, and summarizes meetings in real-time, helping teams stay productive and aligned.",
        features: ["Real-time Transcription", "Automated Meeting Notes", "Speaker Identification", "Action Item Highlights"],
        category: "audio",
        link: "https://otter.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "spline-ai",
        name: "Spline AI",
        description: "Describe what you want to create and let AI generate 3D objects, animations, and scenes.",
        longDescription: "Spline AI allows you to generate 3D objects, scenes, and animations using natural language prompts. It simplifies the complex 3D design process for designers of all levels.",
        features: ["Text-to-3D Generation", "Interactive 3D Experiences", "Collaborative Editing", "Web-based 3D Editor"],
        category: "image",
        link: "https://spline.design/ai",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "character-ai",
        name: "Character.ai",
        description: "Neural language model chatbot service that can generate human-like text responses.",
        longDescription: "Character.ai lets you chat with anyone—real or imagined. From historical figures to fictional characters, their AI platform creates immersive conversational experiences.",
        features: ["Vast Library of AI Personas", "Create Your Own Characters", "Immersive Chat Experiences", "Community Shared Personas"],
        category: "writing",
        link: "https://character.ai",
        badge: "trending",
        pricing: "Free"
    },
    {
        id: "revoicer",
        name: "Revoicer",
        description: "The most realistic AI voiceover generator that expresses human emotions in every voice.",
        longDescription: "Revoicer is the first AI-powered voiceover generator that can express human emotions. It provides a wide range of voices that sound completely natural and engaging.",
        features: ["Emotional Voice Range", "Multi-language Support", "Fast Audio Rendering", "Commercially Safe Voices"],
        category: "audio",
        link: "https://revoicer.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "blackbox-ai",
        name: "Blackbox AI",
        description: "The best AI coding assistant to help you write code faster and search for documentation.",
        longDescription: "Blackbox AI is built to answer coding questions and provide code snippets across 20+ programming languages. It's designed to help developers find solutions without leaving their IDE.",
        features: ["Code Search Engine", "Autocomplete in IDE", "GitHub Integration", "Documentation Assistance"],
        category: "coding",
        link: "https://www.blackbox.ai",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "kaiber",
        name: "Kaiber",
        description: "AI creative lab that helps users generate high-quality video animations from prompts.",
        longDescription: "Kaiber is an AI video generation tool that allows creators to turn their ideas into cinematic animations. It's used by musicians and artists to create stunning visual content.",
        features: ["Visual Storytelling", "Cinematic Animations", "Music Integration", "Style Presets"],
        category: "video",
        link: "https://kaiber.ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "remove-bg",
        name: "Remove.bg",
        description: "Remove image backgrounds automatically in 5 seconds with just one click.",
        longDescription: "Remove.bg uses advanced AI to detect foreground layers and separate them from the background, providing clean transparent images in seconds.",
        features: ["Automated Background Removal", "HD Image Support", "Bulk Processing", "API Integration"],
        category: "image",
        link: "https://www.remove.bg",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "gamma",
        name: "Gamma App",
        description: "A new medium for presenting ideas, powered by AI to create docs, decks, and sites.",
        longDescription: "Gamma allows you to create professional presentations, documents, and even websites from scratch in seconds using their generative AI engine.",
        features: ["Instant Deck Creation", "Interactive Presentations", "No-code Web Pages", "One-click Styling"],
        category: "productivity",
        link: "https://gamma.app",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "murf-ai",
        name: "Murf AI",
        description: "Versatile AI voice generator that enables you to create studio-quality voiceovers.",
        longDescription: "Murf AI provides high-quality AI voices for your videos, presentations, and advertisements. It includes a full-featured studio for timing and voice editing.",
        features: ["Studio-Quality Voices", "Pitch & Speed Control", "Voice Synchronization", "Background Music Library"],
        category: "audio",
        link: "https://murf.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "reword",
        name: "Reword",
        description: "Write better content for your readers with the help of a collaborative AI editor.",
        longDescription: "Reword is a collaborative AI writing assistant that helps you research and write articles that are genuinely helpful to your audience.",
        features: ["Collaborative AI Writing", "Contextual Research", "On-Brand Suggestions", "Internal Linking Help"],
        category: "writing",
        link: "https://reword.ai",
        badge: "new",
        pricing: "Paid"
    },
    {
        id: "phind",
        name: "Phind",
        description: "The intelligent search engine and AI pair programmer for developers.",
        longDescription: "Phind is an answer engine for developers. It provides detailed answers with code snippets to complex technical questions by searching documentation and the web.",
        features: ["Technical Search Engine", "AI Pair Programming", "Documentation Lookup", "Instant Code Solutions"],
        category: "coding",
        link: "https://www.phind.com",
        badge: "",
        pricing: "Free"
    },
    {
        id: "kling",
        name: "Kling AI",
        description: "The latest breakthrough in video generation capable of producing cinematic 1080p clips.",
        longDescription: "Kling AI is a next-generation video model that produces high-fidelity, cinematic video clips from text, showcasing advanced understanding of physics and motion.",
        features: ["1080p Video Generation", "Long Duration Clips", "Physical Realism", "Expressive Avatars"],
        category: "video",
        link: "https://klingai.com",
        badge: "new",
        pricing: "Freemium"
    },
    {
        id: "framer-ai",
        name: "Framer AI",
        description: "Design and publish professional websites with the help of AI in minutes.",
        longDescription: "Framer AI helps you design, ship, and host your dream site with the power of generative AI. Just describe your site and watch it build.",
        features: ["Text-to-Website Generation", "Professional Animations", "CMS Integration", "Global CDN Hosting"],
        category: "productivity",
        link: "https://www.framer.com/ai",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "soundraw",
        name: "Soundraw",
        description: "AI music generator for creators, enabling you to customize every aspect of your tracks.",
        longDescription: "Soundraw is an AI music generator that allows creators to customize length, mood, and genre to create the perfect royalty-free track.",
        features: ["Customizable AI Music", "Mood & Tempo Controls", "Royalty-Free Licensing", "Direct Download"],
        category: "audio",
        link: "https://soundraw.io",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "tabnine",
        name: "Tabnine",
        description: "AI assistant for software developers that helps write code faster with deep learning.",
        longDescription: "Tabnine provides AI-powered code completions based on deep learning models. It supports all popular programming languages and IDEs.",
        features: ["Whole-line Completions", "Privacy-Focused AI", "Local Model Support", "Team Model Training"],
        category: "coding",
        link: "https://www.tabnine.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "invideo",
        name: "InVideo AI",
        description: "Create published-ready videos from simple text ideas with an AI video editor.",
        longDescription: "InVideo AI turns any idea or content into a complete video with script, voiceover, and media in minutes. It's the easiest way to make videos for social media.",
        features: ["Automated Video Editing", "Script Generation", "Voiceover Synthesis", "Library of Stock Media"],
        category: "video",
        link: "https://invideo.io",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "lexica",
        name: "Lexica",
        description: "The search engine for Stable Diffusion images and a powerful generation tool.",
        longDescription: "Lexica is a massive search engine and gallery for images generated with Stable Diffusion. It provides inspiration and prompt ideas for AI artists.",
        features: ["Vast Image Database", "Prompt Search", "Aperture Generation Model", "High-Resolution Gallery"],
        category: "image",
        link: "https://lexica.art",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "summarize-tech",
        name: "Summarize.tech",
        description: "Get a summary of any long YouTube video, like a lecture or an event.",
        longDescription: "Summarize.tech uses AI to provide concise summaries of long YouTube videos, saving you hours of watching time.",
        features: ["YouTube Video Summarization", "Timestamped Highlights", "Key Point Extraction", "Free to Use"],
        category: "productivity",
        link: "https://www.summarize.tech",
        badge: "",
        pricing: "Free"
    },
    {
        id: "voicemod",
        name: "Voicemod",
        description: "Real-time AI voice changer and soundboard for gamers and content creators.",
        category: "audio",
        longDescription: "Voicemod is a real-time AI voice changer that allows users to transform their voice into various characters during live streams or voice chats.",
        features: ["Real-time Voice Effects", "Soundboard Integration", "Support for Discord & Games", "AI Voice Creation"],
        link: "https://www.voicemod.net",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "aider",
        name: "Aider",
        description: "Command line chat tool that allows you to edit code in your local git repo with AI.",
        category: "coding",
        longDescription: "Aider is a CLI tool that lets you pair program with LLMs to edit code in your local git repository. It's designed for serious software development workflows.",
        features: ["CLI Pair Programming", "Git Integration", "Whole Codebase Context", "Support for GPT-4 & Claude 3"],
        link: "https://aider.chat",
        badge: "new",
        pricing: "Free"
    },
    {
        id: "gemini",
        name: "Google Gemini",
        description: "Google's most capable AI model, built to be multimodal and highly efficient.",
        category: "writing",
        longDescription: "Gemini is Google's largest and most capable AI model. It's natively multimodal, meaning it can understand and reason across text, images, video, and audio.",
        features: ["Multimodal Reasoning", "Deep Google Integration", "Advanced Information Retrieval", "Support for Large Datasets"],
        link: "https://gemini.google.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "grok",
        name: "Grok",
        description: "A conversational AI with a bit of wit and real-time access to X (formerly Twitter).",
        category: "writing",
        longDescription: "Grok is an AI built by xAI. It has real-time access to the X platform, allowing it to provide up-to-date information on current events with a unique, witty personality.",
        features: ["Real-time Data from X", "Witty & Rebellious Tone", "Deep Knowledge Search", "Integration with Premium Plus"],
        link: "https://x.ai",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "mistral",
        name: "Mistral AI",
        description: "Efficient and high-performance open-weight models from the French AI startup.",
        category: "coding",
        longDescription: "Mistral AI focuses on building efficient and high-performing open-source AI models. Their models rival the performance of much larger, closed models.",
        features: ["Open-Source Models", "High Efficiency", "Enterprise Deployment", "Custom Model Training"],
        link: "https://mistral.ai",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "cohere",
        name: "Cohere",
        description: "Enterprise AI platform offering NLP solutions for search, generation, and summarization.",
        category: "productivity",
        longDescription: "Cohere provides world-class AI models designed for business. They offer APIs for language generation, text classification, and semantic search.",
        features: ["Enterprise NLP API", "Semantic Search Engine", "Custom Model Fine-tuning", "Privacy-first Architecture"],
        link: "https://cohere.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "huggingface",
        name: "Hugging Face",
        description: "The hub for machine learning models, datasets, and demo apps.",
        category: "coding",
        longDescription: "Hugging Face is the leading community for open-source AI. They provide a massive library of pre-trained models and datasets for every ML task.",
        features: ["Massive Model Hub", "Transformers Library", "Dataset Library", "Inference Endpoints"],
        link: "https://huggingface.co",
        badge: "trending",
        pricing: "Free"
    },
    {
        id: "langchain",
        name: "LangChain",
        description: "Framework for developing applications powered by large language models.",
        category: "coding",
        longDescription: "LangChain is a framework designed to simplify the creation of applications using large language models. It provides a standard interface for chains and agents.",
        features: ["LLM Orchestration", "Memory & Persistence", "Agent Framework", "Integration Ecosystem"],
        link: "https://langchain.com",
        badge: "new",
        pricing: "Free"
    },
    {
        id: "pinecone",
        name: "Pinecone",
        description: "Managed vector database for adding long-term memory to AI applications.",
        category: "coding",
        longDescription: "Pinecone provides the search infrastructure that powers AI applications. Their vector database allows for efficient similarity search at scale.",
        features: ["Vector Similarity Search", "Serverless Infrastructure", "Real-time Data Ingestion", "Scalable Performance"],
        link: "https://www.pinecone.io",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "pika",
        name: "Pika",
        description: "An idea-to-video platform that brings your imagination to life through high-quality video.",
        category: "video",
        longDescription: "Pika is an AI video generation tool that specializes in creating high-quality, expressive animations from text and image prompts.",
        features: ["Text-to-Video Animation", "Style & Character Control", "Video Extension", "Creative Community Hub"],
        link: "https://pika.art",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "synthesia",
        name: "Synthesia",
        description: "AI video generation platform that enables users to create videos with AI avatars.",
        category: "video",
        longDescription: "Synthesia is the world's leading AI video platform for business. It allows you to create studio-quality training and marketing videos using AI avatars.",
        features: ["Custom AI Avatars", "Text-to-Speech in 120 Languages", "Video Editing Studio", "Professional Templates"],
        link: "https://www.synthesia.io",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "pictory",
        name: "Pictory",
        description: "Automatically create short, highly-shareable branded videos from your long-form content.",
        category: "video",
        longDescription: "Pictory uses AI to extract key moments from long-form videos and turn them into short, viral clips for social media automatically.",
        features: ["Automated Highlight Extraction", "Blog Post to Video", "Auto Subtitles", "Branded Video Creation"],
        link: "https://pictory.ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "vidyard",
        name: "Vidyard",
        description: "AI-powered video messaging and hosting platform for business and sales teams.",
        category: "video",
        longDescription: "Vidyard provides video hosting and messaging tools that help sales teams close more deals and marketing teams engage more prospects.",
        features: ["Video Messaging", "Interactive Video Hosting", "Detailed Viewer Analytics", "AI Transcript Generation"],
        link: "https://www.vidyard.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "loom",
        name: "Loom AI",
        description: "Async video communication tool that uses AI to summarize videos and suggest titles.",
        category: "video",
        longDescription: "Loom is a video messaging tool that helps you get your message across through instantly shareable videos. Their AI features help with summarization and editing.",
        features: ["Screen & Cam Recording", "Automated Summaries", "Filler Word Removal", "Instant Video Sharing"],
        link: "https://www.loom.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "adobe-podcast",
        name: "Adobe Podcast",
        description: "AI-powered audio recording and editing, all in the web browser.",
        category: "audio",
        longDescription: "Adobe Podcast provides professional audio recording and editing tools in the browser, with AI features that make anyone sound like they're in a studio.",
        features: ["AI Voice Enhancement", "Mic Check Tool", "Transcript-based Editing", "Remote Recording"],
        link: "https://podcast.adobe.com",
        badge: "",
        pricing: "Free"
    },
    {
        id: "riffusion",
        name: "Riffusion",
        description: "Generate music by using stable diffusion to create images of spectrograms.",
        category: "audio",
        longDescription: "Riffusion is an AI tool that generates music by creating spectrograms through Stable Diffusion. It provides a unique way to visualize and hear AI music.",
        features: ["Visual Music Generation", "Real-time Audio Synthesis", "Prompt-based Riffs", "Interactive Web Interface"],
        link: "https://www.riffusion.com",
        badge: "",
        pricing: "Free"
    },
    {
        id: "mubert",
        name: "Mubert",
        description: "The first AI-generative music ecosystem for creators and brands.",
        category: "audio",
        longDescription: "Mubert provides a generative music platform that creates unique soundtracks for content creators, brands, and apps through a sophisticated AI engine.",
        features: ["Real-time Generative Music", "Music API for Apps", "Royalty-Free Content", "Personalized Music Streams"],
        link: "https://mubert.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "beatoven",
        name: "Beatoven.ai",
        description: "Create unique royalty-free music that fits the mood of your video or podcast.",
        category: "audio",
        longDescription: "Beatoven.ai uses advanced AI music generation techniques to compose unique, mood-based music that perfectly fits the emotional tone of your content.",
        features: ["Mood-based Composition", "Sectional Editing", "Royalty-Free Licensing", "Genre Diversity"],
        link: "https://www.beatoven.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "lalal",
        name: "Lalal.ai",
        description: "High-quality stem splitting based on the world's number one AI-powered technology.",
        category: "audio",
        longDescription: "Lalal.ai is a next-generation vocal remover and music source separation service for fast, easy and precise stem extraction from any audio or video.",
        features: ["High-Precision Stem Splitting", "Vocal & Instrumental Extraction", "Fast Processing", "Bulk Audio Support"],
        link: "https://www.lalal.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "quillbot",
        name: "Quillbot",
        description: "AI-powered paraphrasing tool that helps you write better and faster.",
        category: "writing",
        longDescription: "Quillbot is a comprehensive writing tool that includes an AI paraphraser, grammar checker, and plagiarism detector to help students and professionals improve their writing.",
        features: ["AI Paraphrasing Engine", "Advanced Grammar Checker", "Plagiarism Detection", "Summarization Tool"],
        link: "https://quillbot.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "writesonic",
        name: "Writesonic",
        description: "AI writing tool that creates high-quality content for blogs, ads, and emails.",
        category: "writing",
        longDescription: "Writesonic is an AI writing platform that helps marketing teams generate articles, ad copy, and landing pages with built-in SEO optimization.",
        features: ["SEO Content Generator", "AI Article Writer 6.0", "Marketing Copy Templates", "Bulk Content Generation"],
        link: "https://writesonic.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "rytr",
        name: "Rytr",
        description: "AI writing assistant that helps you create high-quality content in just a few seconds.",
        category: "writing",
        longDescription: "Rytr is an AI writing assistant that helps you create high-quality content, from emails to blogs, in just a few seconds at a fraction of the cost.",
        features: ["Multi-language Support", "40+ Use Cases", "Tone Selection", "Built-in Plagiarism Checker"],
        link: "https://rytr.me",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "sudowrite",
        name: "Sudowrite",
        description: "The AI writing partner you've always wanted for your next novel or story.",
        category: "writing",
        longDescription: "Sudowrite is a creative writing assistant designed for fiction writers. It helps with brainstorming, descriptive writing, and overcoming writer's block.",
        features: ["Story Brainstorming", "Sensory Description Help", "Plot Point Expansion", "Character Development"],
        link: "https://www.sudowrite.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "wordtune",
        name: "Wordtune",
        description: "AI-powered writing companion that helps you rephrase and refine your sentences.",
        category: "writing",
        longDescription: "Wordtune is a generative AI platform that helps you rewrite your thoughts in more clear, compelling, and authentic ways.",
        features: ["Sentence Rewriting", "Summarization Tool", "Personalized Recommendations", "Contextual Corrections"],
        link: "https://www.wordtune.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "hemingway",
        name: "Hemingway Editor",
        description: "The app that highlights lengthy, complex sentences and common errors.",
        category: "writing",
        longDescription: "Hemingway Editor makes your writing bold and clear. It uses AI to highlight wordy sentences and common writing mistakes that detract from your message.",
        features: ["Readability Scoring", "Common Error Highlighting", "Sentence Length Analysis", "Passive Voice Detection"],
        link: "https://hemingwayapp.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "frase",
        name: "Frase",
        description: "AI content platform that helps you research, write, and optimize SEO content.",
        category: "writing",
        longDescription: "Frase helps SEOs and content marketers research and write content that ranks. It provides detailed content briefs based on search engine results.",
        features: ["AI Content Briefs", "SEO Optimization Tool", "Answer Engine Support", "Content Analytics Integration"],
        link: "https://www.frase.io",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "anyword",
        name: "Anyword",
        description: "Data-driven copywriting platform that predicts how your audience will react.",
        category: "writing",
        longDescription: "Anyword is the first AI copywriting platform to offer a predictive performance score, so you can see how different copy will perform with your audience.",
        features: ["Predictive Performance Score", "Audience-Specific Copy", "Ad Copy Generation", "Brand Voice Maintenance"],
        link: "https://anyword.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "hypotenuse",
        name: "Hypotenuse AI",
        description: "Streamline your content writing with AI that researchers and writes for you.",
        category: "writing",
        longDescription: "Hypotenuse AI simplifies the content creation process by researching, writing, and optimizing your articles and product descriptions in one place.",
        features: ["Bulk Content Production", "E-commerce Optimization", "AI Blog Generation", "Fact-Checking Engine"],
        link: "https://www.hypotenuse.ai",
        badge: "new",
        pricing: "Paid"
    },
    {
        id: "copysmith",
        name: "CopySmith",
        description: "AI copywriting platform for e-commerce teams and agencies.",
        category: "writing",
        longDescription: "Copysmith is an enterprise AI platform that enables marketing teams to scale high-quality content production and management across their organization.",
        features: ["E-commerce Product Copy", "Bulk Content Generation", "Campaign Builder", "Team Collaboration Tools"],
        link: "https://copysmith.ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "typeface",
        name: "Typeface",
        description: "Enterprise-grade generative AI for hyper-personalized content creation.",
        category: "writing",
        longDescription: "Typeface is a personalized AI platform for enterprise content. It allows businesses to create high-quality, on-brand content at scale.",
        features: ["Brand Personality Engine", "Multi-modal Generation", "Secure Enterprise Architecture", "Template Library"],
        link: "https://www.typeface.ai",
        badge: "new",
        pricing: "Paid"
    },
    {
        id: "contentbot",
        name: "ContentBot",
        description: "Advanced AI writing assistant for creators, marketers, and businesses.",
        category: "writing",
        longDescription: "ContentBot is an advanced AI writing tool that offers a wide range of features from short-form copy to full-length articles and automated workflows.",
        features: ["Full Blog Post Writer", "AI Marketing Workflows", "Browser Extension Support", "Multi-language Generation"],
        link: "https://contentbot.ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "meetgeek",
        name: "MeetGeek",
        description: "AI meeting assistant that record, transcribe and share highlights of your meetings.",
        category: "productivity",
        longDescription: "MeetGeek is an AI-powered meeting recording and transcription service that automatically captures insights from your video calls.",
        features: ["Automated Meeting Capture", "Transcript Highlights", "Meeting Analytics", "Cross-Platform Support"],
        link: "https://meetgeek.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "read-ai",
        name: "Read AI",
        description: "AI for meetings, email, and chat that provides summaries and insights.",
        category: "productivity",
        longDescription: "Read AI generates automated summaries, action items, and insights across all your communication channels like Zoom, Teams, Slack, and Email.",
        features: ["Communication Intelligence", "Automated Summaries", "Meeting Engagement Metrics", "Team Performance Insights"],
        link: "https://www.read.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "krisp",
        name: "Krisp",
        description: "AI noise-canceling app that removes background noise from your calls.",
        category: "productivity",
        longDescription: "Krisp is a world-leading noise-canceling app that uses AI to remove background noise, echo, and voices from your online calls in real-time.",
        features: ["Real-time Noise Removal", "Acoustic Echo Cancellation", "Voice Clarity Enhancement", "Works with 800+ Meeting Apps"],
        link: "https://krisp.ai",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "sanebox",
        name: "SaneBox",
        description: "AI-powered email management that cleans up your inbox automatically.",
        category: "productivity",
        longDescription: "SaneBox uses sophisticated AI to analyze your email history and automatically sort incoming mail into important and less-important folders.",
        features: ["Automated Email Sorting", "Unsubscribe with One Click", "SaneBlackHole Feature", "Email Reminder System"],
        link: "https://www.sanebox.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "motion",
        name: "Motion",
        description: "AI calendar and task manager that automatically builds your schedule.",
        category: "productivity",
        longDescription: "Motion uses AI to plan your day. It automatically builds a schedule for your tasks and meetings, rearranging them as your day changes.",
        features: ["Intelligent Day Planning", "Automated Task Scheduling", "Meeting Booking System", "Focus Time Protection"],
        link: "https://www.usemotion.com",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "akiflow",
        name: "Akiflow",
        description: "Centralized task manager and calendar that uses AI to optimize your day.",
        category: "productivity",
        longDescription: "Akiflow is a productivity tool that brings all your tasks and calendar events into a single view, with AI features to help you prioritize.",
        features: ["Unified Task Inbox", "Command Bar Shortcuts", "Time Blocking Engine", "Integration with 2000+ Apps"],
        link: "https://akiflow.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "clockwise",
        name: "Clockwise",
        description: "Smart calendar assistant that optimizes your schedule for focus time.",
        category: "productivity",
        longDescription: "Clockwise is an AI-powered calendar assistant that optimizes your team's schedule to create blocks of uninterrupted focus time.",
        features: ["Focus Time Optimization", "Automatic Meeting Moving", "Team Sync Features", "Calendar Productivity Stats"],
        link: "https://www.getclockwise.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "superhuman",
        name: "Superhuman",
        description: "The fastest email experience ever made, enhanced with powerful AI.",
        category: "productivity",
        longDescription: "Superhuman provides a blazingly fast email experience with built-in AI features that help you write better emails and get to Inbox Zero faster.",
        features: ["AI Email Composition", "Advanced Search Engine", "Split Inbox Layout", "Read Receipts & Reminders"],
        link: "https://superhuman.com",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "magical",
        name: "Magical",
        description: "AI automation tool that speeds up repetitive tasks across any web app.",
        category: "productivity",
        longDescription: "Magical is a productivity app that uses AI to automate repetitive tasks like data entry and messaging across any website or application.",
        features: ["No-Code Task Automation", "Instant Messaging Shortcuts", "Data Scraping Capabilities", "AI Writing Support"],
        link: "https://www.getmagical.com",
        badge: "",
        pricing: "Free"
    },
    {
        id: "mem",
        name: "Mem",
        description: "AI-powered workspace that organizes your thoughts and information.",
        category: "productivity",
        longDescription: "Mem is the world's first AI-powered workspace that's personalized to you. It automatically organizes your notes, links, and documents.",
        features: ["Self-Organizing Workspace", "AI Search & Retrieval", "Contextual Information Linking", "Mobile Capture Tool"],
        link: "https://mem.ai",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "taskade",
        name: "Taskade",
        description: "The AI-powered productivity platform for modern teams.",
        category: "productivity",
        longDescription: "Taskade is an all-in-one productivity platform for teams. It includes AI-powered task lists, mind maps, and chat in one workspace.",
        features: ["AI Project Management", "Dynamic Mind Mapping", "Real-time Collaboration", "Task Automation Workflows"],
        link: "https://www.taskade.com",
        badge: "",
        pricing: "Freemium"
    },
    {
        id: "clickup-brain",
        name: "ClickUp Brain",
        description: "The first neural network that connects your tasks, docs, people, and company knowledge.",
        category: "productivity",
        longDescription: "ClickUp Brain is a revolutionary AI built into ClickUp that helps you find answers, write updates, and automate your entire project workflow.",
        features: ["Neural Knowledge Search", "Automated Project Updates", "AI Writing Assistant", "Workflow Automation Builder"],
        link: "https://clickup.com/features/ai",
        badge: "trending",
        pricing: "Paid"
    },
    {
        id: "asana-intelligence",
        name: "Asana Intelligence",
        description: "AI for work management to help teams work smarter and faster.",
        category: "productivity",
        longDescription: "Asana Intelligence provides AI features that help teams optimize their workflows, identify bottlenecks, and stay aligned on their goals.",
        features: ["Resource Management AI", "Automated Status Reports", "Workflow Optimization", "Predictive Analytics"],
        link: "https://asana.com/product/ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "monday-ai",
        name: "Monday.com AI",
        description: "Empower your team to work faster and more efficiently with AI-powered automations.",
        category: "productivity",
        longDescription: "Monday.com AI helps teams build custom workflows and automations with ease, using generative AI to simplify complex project management tasks.",
        features: ["No-Code AI Automations", "Intelligent Board Setup", "Automated Data Analysis", "Team Alignment Tools"],
        link: "https://monday.com/ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "krea",
        name: "Krea.ai",
        description: "Real-time AI creative tool for high-quality image generation and enhancement.",
        category: "image",
        longDescription: "Krea.ai is a real-time creative platform that allows you to generate and upscale images instantly, providing a powerful workflow for professional artists.",
        features: ["Real-time Image Generation", "Advanced Upscaling Model", "Creative Prompt Library", "Professional Workflow Tools"],
        link: "https://www.krea.ai",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "magnific",
        name: "Magnific AI",
        description: "The most advanced AI image upscaler and enhancer for professional creators.",
        category: "image",
        longDescription: "Magnific is a state-of-the-art AI image upscaler and enhancer that uses sophisticated models to add incredible detail and resolution to any image.",
        features: ["Extreme Upscaling Tech", "Detail Reconstruction", "Artistic Style Controls", "High-Resolution Export"],
        link: "https://magnific.ai",
        badge: "new",
        pricing: "Paid"
    },
    {
        id: "clipdrop",
        name: "ClipDrop",
        description: "A suite of AI tools for creators to edit and generate high-quality visuals.",
        category: "image",
        longDescription: "ClipDrop provides a comprehensive suite of AI tools for image editing, including background removal, relighting, and generative fill.",
        features: ["AI Image Relighting", "Instant Object Removal", "High-Def Upscaling", "Stable Diffusion Integration"],
        link: "https://clipdrop.co",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "vectormagic",
        name: "Vector Magic",
        description: "Automatically convert bitmap images like JPEGs and PNGs to clean vector art.",
        category: "image",
        longDescription: "Vector Magic uses advanced AI algorithms to convert raster images into high-quality, scalable vector graphics automatically.",
        features: ["Automated Vectorization", "High-Precision Edge Tracing", "Color Optimization", "Multiple Export Formats"],
        link: "https://vectormagic.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "looka",
        name: "Looka",
        description: "AI-powered logo maker and brand identity platform for entrepreneurs.",
        category: "image",
        longDescription: "Looka helps entrepreneurs design professional logos and brand identities in minutes using a sophisticated AI design engine.",
        features: ["AI Logo Designer", "Brand Kit Generation", "Social Media Templates", "Website Brand Integration"],
        link: "https://looka.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "brandmark",
        name: "Brandmark",
        description: "Create a professional logo and brand identity with AI in minutes.",
        category: "image",
        longDescription: "Brandmark provides a simple yet powerful AI logo maker that generates thousands of unique logo options based on your brand values.",
        features: ["Instant Logo Generation", "Typography Matching", "Color Palette Creation", "Brand Guide Support"],
        link: "https://brandmark.io",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "designs-ai",
        name: "Designs.ai",
        description: "AI-powered platform to create logos, videos, and social media content.",
        category: "image",
        longDescription: "Designs.ai is an integrated creative platform that uses AI to help you create logos, videos, and social media content in one place.",
        features: ["Logo & Brand Maker", "AI Video Generator", "Graphic Design Suite", "Mockup Creator"],
        link: "https://designs.ai",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "uizard",
        name: "Uizard",
        description: "Design mobile apps, websites, and wireframes in minutes with AI.",
        category: "image",
        longDescription: "Uizard is an AI-powered design tool for creating mobile apps and websites. It can turn hand-drawn sketches into professional digital designs instantly.",
        features: ["Sketch-to-Design AI", "Interactive Prototyping", "UI Component Library", "Design Collaboration Hub"],
        link: "https://uizard.io",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "ms-designer",
        name: "Microsoft Designer",
        description: "Create stunning visuals and social media posts with DALL-E 3 integration.",
        category: "image",
        longDescription: "Microsoft Designer is a cloud-based design tool that uses DALL-E 3 to help you create professional-quality graphics and social media content.",
        features: ["DALL-E 3 Integration", "Automated Layout Design", "Social Media Optimizer", "Cloud Sync Support"],
        link: "https://designer.microsoft.com",
        badge: "new",
        pricing: "Free"
    },
    {
        id: "filmora",
        name: "Wondershare Filmora",
        description: "Easy-to-use video editor with powerful AI features like smart cutout and auto reframe.",
        category: "video",
        longDescription: "Filmora is a versatile video editor that includes several AI-powered features like smart cutout, background removal, and automatic video re-framing.",
        features: ["AI Smart Cutout", "Automated Background Removal", "Intelligent Video Reframe", "AI-Powered Text-to-Speech"],
        link: "https://filmora.wondershare.com",
        badge: "",
        pricing: "Paid"
    },
    {
        id: "tabby",
        name: "Tabby",
        description: "A self-hosted AI coding assistant, an open-source alternative to GitHub Copilot.",
        category: "coding",
        longDescription: "Tabby is an open-source, self-hosted AI coding assistant that provides developers with a private alternative to cloud-based AI tools.",
        features: ["Self-Hosted Infrastructure", "Private Model Support", "IDE Integration", "Open Source Core"],
        link: "https://tabby.ml",
        badge: "new",
        pricing: "Free"
    },
    {
        id: "mintlify",
        name: "Mintlify",
        description: "AI-powered documentation that builds itself and helps developers ship faster.",
        category: "coding",
        longDescription: "Mintlify uses AI to scan your codebase and automatically generate professional documentation that's easy for other developers to understand.",
        features: ["Automated Documentation", "Codebase Scanning", "Interactive Doc Search", "Modern Web-based Hosting"],
        link: "https://mintlify.com",
        badge: "trending",
        pricing: "Freemium"
    },
    {
        id: "vimeo-ai",
        name: "Vimeo AI",
        description: "Create, edit, and share professional videos with the help of AI-powered tools.",
        category: "video",
        longDescription: "Vimeo AI provides a suite of tools that help creators and businesses edit videos faster and optimize them for their target audience.",
        features: ["AI Video Editor", "Automated Summarization", "Intelligent Video Hosting", "Detailed Engagement Stats"],
        link: "https://vimeo.com/features/ai-video-editing",
        badge: "",
        pricing: "Freemium"
    }
];
